apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: redis-app
          image: redis:5.0
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-conf-vol
              mountPath: "/usr/local/etc"
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          resources:
            requests:
              cpu: "500m"
              memory: "200Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
      volumes:
        - name: redis-conf-vol
          configMap:
            name: redis-conf
            items:
              - key: redis.conf
                path: redis/redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redisvc
spec:
  ports:
    - port: 6379
  selector:
    app: redis-app
  type: ClusterIP
